const BASE_URL = 'http://localhost:8080';

// 书籍接口定义
export interface Book {
  id: number;
  name: string;
  title: string;
  author: string;
  description: string;
  created_at?: string;
}

export interface BookStats {
  totalBooks: number;
  totalFiles: number;
  filesByBook: Array<{
    bookId: number;
    bookName: string;
    fileCount: number;
  }>;
}

export interface BookListResponse {
  books: Book[];
  total: number;
}

// 文件接口定义
export interface MarkdownFile {
  id: number;
  file_path: string;
  property: string;
  book_id: number;
  created_at: string;
  updated_at: string;
}

export interface SummaryResponse {
  content: string;
  autoGenerated?: boolean;
  error?: string;
}

// 通用API请求处理函数
async function handleApiRequest<T>(url: string, options: RequestInit = {}): Promise<T> {
  try {
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(errorData.error || `HTTP ${response.status}: ${response.statusText}`);
    }
    return await response.json();
  } catch (error) {
    console.error('[API错误]', error);
    throw error;
  }
}

// 书籍管理API
export const bookApi = {
  // 获取所有书籍
  async getAllBooks(): Promise<BookListResponse> {
    return handleApiRequest<BookListResponse>(`${BASE_URL}/api/books`);
  },

  // 获取特定书籍
  async getBook(id: number): Promise<Book> {
    return handleApiRequest<Book>(`${BASE_URL}/api/books/${id}`);
  },

  // 创建新书籍
  async createBook(bookData: Omit<Book, 'id' | 'created_at'>): Promise<Book> {
    return handleApiRequest<Book>(`${BASE_URL}/api/books`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(bookData),
    });
  },

  // 更新书籍信息
  async updateBook(id: number, bookData: Partial<Book>): Promise<Book> {
    return handleApiRequest<Book>(`${BASE_URL}/api/books/${id}`, {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(bookData),
    });
  },

  // 删除书籍
  async deleteBook(id: number): Promise<{ message: string }> {
    return handleApiRequest<{ message: string }>(`${BASE_URL}/api/books/${id}`, {
      method: 'DELETE',
    });
  },

  // 获取书籍统计
  async getBookStats(): Promise<BookStats> {
    return handleApiRequest<BookStats>(`${BASE_URL}/api/books/stats`);
  },
};

// 文件管理API（支持bookId参数）
export const fileApi = {
  // 获取Markdown文件列表
  async getMarkdownFiles(bookId?: number): Promise<{ files: MarkdownFile[]; total: number }> {
    const url = bookId 
      ? `${BASE_URL}/api/files/markdown?bookId=${bookId}`
      : `${BASE_URL}/api/files/markdown`;
    return handleApiRequest<{ files: MarkdownFile[]; total: number }>(url);
  },

  // 获取章节文件
  async getChapterFiles(property: string, bookId?: number): Promise<{ files: MarkdownFile[]; total: number }> {
    const url = bookId 
      ? `${BASE_URL}/api/files/${property}?bookId=${bookId}`
      : `${BASE_URL}/api/files/${property}`;
    return handleApiRequest<{ files: MarkdownFile[]; total: number }>(url);
  },

  // 获取章节摘要
  async getSummary(property: string, bookId?: number, brief: boolean = false, autoGenerate: boolean = true): Promise<SummaryResponse> {
    const url = bookId 
      ? `${BASE_URL}/api/files/summary/${property}?bookId=${bookId}&brief=${brief}&autoGenerate=${autoGenerate}`
      : `${BASE_URL}/api/files/summary/${property}?brief=${brief}&autoGenerate=${autoGenerate}`;
    return handleApiRequest<SummaryResponse>(url);
  },

  // 获取所有摘要
  async getAllSummaries(bookId?: number): Promise<{ summaries: any[]; total: number }> {
    const url = bookId 
      ? `${BASE_URL}/api/files/summaries?bookId=${bookId}`
      : `${BASE_URL}/api/files/summaries`;
    return handleApiRequest<{ summaries: any[]; total: number }>(url);
  },

  // 获取图片文件夹
  async getImageFiles(property: string, bookId?: number): Promise<{ files: MarkdownFile[]; total: number }> {
    const url = bookId 
      ? `${BASE_URL}/api/files/chapter/${property}/images?bookId=${bookId}`
      : `${BASE_URL}/api/files/chapter/${property}/images`;
    return handleApiRequest<{ files: MarkdownFile[]; total: number }>(url);
  },

  // 获取表格文件夹
  async getTableFiles(property: string, bookId?: number): Promise<{ files: MarkdownFile[]; total: number }> {
    const url = bookId 
      ? `${BASE_URL}/api/files/chapter/${property}/tables?bookId=${bookId}`
      : `${BASE_URL}/api/files/chapter/${property}/tables`;
    return handleApiRequest<{ files: MarkdownFile[]; total: number }>(url);
  },

  // 获取目录结构
  async getTocChapters(bookId?: number): Promise<any> {
    const url = bookId 
      ? `${BASE_URL}/api/files/toc/chapters?bookId=${bookId}`
      : `${BASE_URL}/api/files/toc/chapters`;
    return handleApiRequest<any>(url);
  },

  // 获取带摘要的目录结构
  async getTocWithSummaries(bookId?: number): Promise<any> {
    const url = bookId 
      ? `${BASE_URL}/api/files/toc-with-summaries?bookId=${bookId}`
      : `${BASE_URL}/api/files/toc-with-summaries`;
    return handleApiRequest<any>(url);
  },

  // 搜索文件
  async searchFiles(keyword: string, bookId?: number): Promise<{ files: MarkdownFile[]; total: number }> {
    const url = bookId 
      ? `${BASE_URL}/api/files/search?keyword=${encodeURIComponent(keyword)}&bookId=${bookId}`
      : `${BASE_URL}/api/files/search?keyword=${encodeURIComponent(keyword)}`;
    return handleApiRequest<{ files: MarkdownFile[]; total: number }>(url);
  },

  // 获取文件统计
  async getFileStats(bookId?: number): Promise<any> {
    const url = bookId 
      ? `${BASE_URL}/api/files/stats?bookId=${bookId}`
      : `${BASE_URL}/api/files/stats`;
    return handleApiRequest<any>(url);
  },
};

// 文件上传API（支持bookId参数）
export const uploadApi = {
  // 上传单个或多个文件
  async uploadFiles(files: File[], bookId?: number): Promise<any> {
    const formData = new FormData();
    files.forEach(file => formData.append('files', file));
    if (bookId) {
      formData.append('bookId', bookId.toString());
    }
    
    return handleApiRequest<any>(`${BASE_URL}/api/upload/files`, {
      method: 'POST',
      body: formData,
    });
  },

  // 上传图片文件夹
  async uploadImageFolder(folderName: string, files: File[], bookId?: number): Promise<any> {
    const formData = new FormData();
    formData.append('folderName', folderName);
    files.forEach(file => formData.append('files', file));
    if (bookId) {
      formData.append('bookId', bookId.toString());
    }
    
    return handleApiRequest<any>(`${BASE_URL}/api/upload/folder`, {
      method: 'POST',
      body: formData,
    });
  },

  // 上传摘要文件
  async uploadSummary(property: string, file: File, bookId?: number): Promise<any> {
    const formData = new FormData();
    formData.append('property', property);
    formData.append('file', file);
    if (bookId) {
      formData.append('bookId', bookId.toString());
    }
    
    return handleApiRequest<any>(`${BASE_URL}/api/upload/summary`, {
      method: 'POST',
      body: formData,
    });
  },

  // 上传表格文件夹
  async uploadTableFolder(folderName: string, files: File[], bookId?: number): Promise<any> {
    const formData = new FormData();
    formData.append('folderName', folderName);
    files.forEach(file => formData.append('files', file));
    if (bookId) {
      formData.append('bookId', bookId.toString());
    }
    
    return handleApiRequest<any>(`${BASE_URL}/api/upload/table-folder`, {
      method: 'POST',
      body: formData,
    });
  },
};
